# Generated by Django 4.2.6 on 2024-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("discount", models.FloatField()),
            ],
        ),
    ]
