# Generated by Django 5.0.1 on 2024-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_offer_code_alter_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
