# Generated by Django 5.0.1 on 2024-01-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_offer_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
